emulators:
 samsung:
   caps:
     deviceName:	"Nexus"
     platformName:	"Android"
     version:	"6.0"				#setar	a	versão	do	android	utilizado	no	device
     app:	"/home/priscila/appium/TrianguloApp.apk"
     appPackage:	"com.eliasnogueira.trianguloapp"
     appActivity:	"com.eliasnogueira.trianguloapp.MainActivity"
     newCommandTimeout:	"3600"
     port:	4723
     appium_port:	4723
     appium_lib:	{	wait:	20,	debug:	false}
